routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('admin')
    ->namespace('Admin')
    ->group(function () {
        Route::get('/', 'DashboardController@index')
            ->name('dashboard');

        Route::resource('buku', 'DataBukuController');
        Route::resource('gallery', 'BookGalleryController');
    });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/buku/create.blade.php
@extends('layouts.default')
@section('title','Data Buku')
@section('content')
    <div class="container d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Data Buku</h1>
    </div>


        <div class="card-shadow">
            <div class="card-body">
                <form action="{{route('buku.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="kode">Kode Buku</label>
                        <input type="text" name="kode" class="form-control @error('kode') is_invalid @enderror" value="{{old('kode')}}" required> @error('kode') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="judul">Judul Buku</label>
                        <input type="text" name="judul" class="form-control @error('judul') is_invalid @enderror" value="{{old('judul')}}" required> @error('judul') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="penulis">Penulis Buku</label>
                        <input type="text" name="penulis" class="form-control @error('penulis') is_invalid @enderror" value="{{old('penulis')}}" required> @error('penulis') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="penerbit">Penerbit Buku</label>
                        <input type="text" name="penerbit" class="form-control @error('penerbit') is_invalid @enderror" value="{{old('penerbit')}}" required> @error('penerbit') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="tahun_terbit">Tahun Terbit</label>
                        <input type="date" name="tahun_terbit" class="form-control @error('tahun_terbit') is_invalid @enderror" value="{{old('tahun_terbit')}}" required> @error('tahun_terbit') <div class="text-muted">{{$message}}</div> @enderror
                    </div>

                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-save"></i> Simpan
                    </button>
                    <button class="btn btn-danger" type="reset">
                        <i class="fas fa-recycle"></i> Reset
                    </button>
                </form>
            </div>
        </div>
@endsection

resources/views/pages/buku/edit.blade.php
@extends('layouts.default')
@section('title','Data Buku')
@section('content')
    <div class="container d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Data Buku</h1>
    </div>


        <div class="card-shadow">
            <div class="card-body">
                <form action="{{route('buku.update',$item->id)}}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="kode">Kode Buku</label>
                        <input type="text" name="kode" class="form-control @error('kode') is_invalid @enderror" value="{{$item->kode}}" required> @error('kode') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="judul">Judul Buku</label>
                        <input type="text" name="judul" class="form-control @error('judul') is_invalid @enderror" value="{{$item->judul}}" required> @error('judul') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="penulis">Penulis Buku</label>
                        <input type="text" name="penulis" class="form-control @error('penulis') is_invalid @enderror" value="{{$item->penulis}}" required> @error('penulis') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="penerbit">Penerbit Buku</label>
                        <input type="text" name="penerbit" class="form-control @error('penerbit') is_invalid @enderror" value="{{$item->penerbit}}" required> @error('penerbit') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="tahun_terbit">Tahun Terbit</label>
                        <input type="date" name="tahun_terbit" class="form-control @error('tahun_terbit') is_invalid @enderror" value="{{$item->tahun_terbit}}" required> @error('tahun_terbit') <div class="text-muted">{{$message}}</div> @enderror
                    </div>

                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-save"></i> Simpan
                    </button>
                    <button class="btn btn-danger" type="reset">
                        <i class="fas fa-recycle"></i> Reset
                    </button>
                </form>
            </div>
        </div>
@endsection

resources/views/pages/buku/index.blade.php
@extends('layouts.default')
@section('title','Data Buku')
@section('content')
    <div class="container d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Buku</h1>
        <a href="{{route('buku.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Tambah Data Buku</a>
    </div>

        <div class="card-shadow">
            <div class="card-body">
                @if (session('sukses'))
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button class="close" type="button" data-dismiss="alert" aria-label="close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <i class="fa fa-circle-check"></i>
                        {{session('sukses')}}
                    </div>
                @endif
                @if (session('hapus'))
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button class="close" type="button" data-dismiss="alert" aria-label="close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <i class="fa fa-check"></i>
                        {{session('hapus')}}
                    </div>
                @endif
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kode Buku</th>
                                <th>Judul Buku</th>
                                <th>Penulis</th>
                                <th>Penerbit</th>
                                <th>Tahun Terbit</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no = 1 ?>
                            @forelse ($items as $item)
                                <tr>
                                    <td>{{$no}}</td>
                                    <td>{{$item->kode}}</td>
                                    <td>{{$item->judul}}</td>
                                    <td>{{$item->penulis}}</td>
                                    <td>{{$item->penerbit}}</td>
                                    <td>{{$item->tahun_terbit}}</td>
                                    <td>
                                        <a href="" class="btn btn-info">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        <a href="{{route('buku.edit', $item->id)}}" class="btn btn-warning">
                                            <i class="fa fa-pencil-alt"></i>
                                        </a>
                                        <form action="{{route('buku.destroy', $item->id)}}" method="POST" class="d-inline">
                                            @method('delete')
                                            @csrf
                                            <button class="btn btn-danger">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                    <?php $no++ ?>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center">
                                        Data Buku Kosong
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
@endsection